spring:
  application:
    name: lifemate-rest-api
  profiles:
    active: dev

server:
  port: 8888

---

spring:
  application:
    name: lifemate-rest-api
  profiles:
    active: prod

server:
  port: 8888